### ISSUE TITLE
Error: Cannot find mpih-mul.c:85 in gpg-1.4.13

### ISSUE THREAD

**Issue by JaspinderKaur07** [Sanghyun-Hong/Mastik#2]
What i did: sudo ./config
sudo./make
then inside demo folder :
**:~/Downloads/Mastik-0.02-AyeAyeCapn/demo$ sudo ./FF-gnupg-1.4.13
[sudo] password for calab: 
Cannot find mpih-mul.c:85 in gpg-1.4.13**

**Comment by Sanghyun-Hong** [comment]
Hi @JaspinderKaur07, 
I think what you're running requires the source code of your Linux system (e.g., **mpih-mul.c**). Keep in mind that this is just a repository for the Mastik code. For further information, you can contact the authors.

Thanks
